- hosts: localhost
  tasks:
    ### VirtFS Prometheus Exporter
    - name: Install dependencies
      apt:
        name: ["python3-pip", "python3-libvirt", "systemd-container", "libguestfs-tools", "sysstat"]
        state: present
      tags: install

    - name: Check pip3 local path
      stat:
        path: /usr/local/bin/pip3
      register: pip3_local
      tags: install

    - name: Install prometheus_client
      pip:
        name: prometheus_client
        state: present
        executable: /usr/local/bin/pip3
      register: prom_c
      when: pip3_local.stat.exists
      tags: install

    - name: Install prometheus_client
      pip:
        name: prometheus_client
        state: present
        executable: /usr/bin/pip3
      register: prom_c
      when: pip3_local.stat.exists == false
      tags: install

    - name: Create virtfs exporter directory
      file:
        path: /opt/virtfs_exporter
        state: directory
        mode: '0755'
      tags: install

    - name: Place libvirt metadata manager
      copy:
        src: libvirtmetadata.py
        dest: /opt/virtfs_exporter/libvirtmetadata.py
      register: lm
      tags: install

    - name: Place task scheduler
      copy:
        src: scheduler.py
        dest: /opt/virtfs_exporter/scheduler.py
      register: ts
      tags: install

    - name: Place virtfs exporter
      copy:
        src: virtfs_exporter.py
        dest: /opt/virtfs_exporter/virtfs_exporter.py
      register: exporter
      tags: install

    - name: Render virtfs_exporter service template
      template:
        src: virtfs_exporter.service.j2
        dest: /etc/systemd/system/virtfs_exporter.service
        mode: 0644
      register: service
      tags: install

    - name: Restart and assured enabled virtfs_exporter
      systemd:
        name: virtfs_exporter
        state: restarted
        enabled: yes
        daemon-reload: "{{ service.changed }}"
      register: service_restart
      when: exporter.changed or lm.changed or ts.changed or prom_c.changed or service.changed
      ignore_errors: yes
      tags: install

    - name: Start and enable virtfs_exporter
      systemd:
        name: virtfs_exporter
        state: started
        enabled: yes
      when: service_restart is skipped
      ignore_errors: yes
      tags: install

    - name: Assure started and enabled virtfs_exporter
      systemd:
        name: virtfs_exporter
        state: started
        enabled: yes
      tags: never, start

    - name: Stop and disable virtfs_exporter
      systemd:
        name: virtfs_exporter
        state: stopped
        enabled: no
      ignore_errors: yes
      tags: never, uninstall
