name: ci
on:
  push:
    branches: master
  pull_request:
    branches: master
jobs:
  lint:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - run: python3 -m pip install tox
      - name: Run linter
        run: make lint
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8.x'
      - name: Set up lxd
        run: |
          sudo usermod --append --groups lxd $(whoami)
          sudo su $(whoami) -c 'lxd init --auto'
          sudo su $(whoami) -c 'lxc network set lxdbr0 ipv6.address none'
      - name: Install charmcraft
        run: sudo snap install charmcraft --classic --stable
      - name: Build charm
        run: |
          sudo su $(whoami) -c 'charmcraft build --verbose --from .'
          mv prometheus-virtfs-exporter_ubuntu-16.04-amd64_ubuntu-18.04-amd64_ubuntu-20.04-amd64.charm prometheus-virtfs-exporter.charm
      - name: Upload charm artifact
        uses: actions/upload-artifact@v2
        with:
          name: charm
          path: prometheus-virtfs-exporter.charm
  test:
    runs-on: ubuntu-20.04
    needs: build
    strategy:
      fail-fast: false
      matrix:
        juju_channel:
          - 2.7/stable
          - 2.8/stable
        test_bundles:
          - xenial-bundle
          - bionic-bundle
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8.x'
      - run: python3 -m pip install tox
      - name: Download charm artifact
        uses: actions/download-artifact@v2
        with:
          name: charm
          path: /tmp/charm-builds
      - name: Show charm content
        run: |
          ls -la /tmp/charm-builds
          ls -la /tmp/charm-builds/prometheus-virtfs-exporter.charm
      # - name: Set charm location
      #   run: |
      #     mkdir -p /tmp/charm-builds
      #     mv prometheus-virtfs-exporter.charm /tmp/charm-builds/prometheus-virtfs-exporter.charm
      - name: Set up LXD
        run: |
          sudo usermod --append --groups lxd $(whoami)
          sudo su $(whoami) -c 'lxd init --auto'
          sudo su $(whoami) -c 'lxc network set lxdbr0 ipv6.address none'
      - name: Change ownership of root workaround for snapcraft
        # See https://forum.snapcraft.io/t/permissions-problem-using-snapcraft-in-azure-pipelines/13258/14?u=szeestraten
        run: sudo chown root:root /
      - name: Set up juju
        run: |
          sudo snap install juju --classic --channel=${{ matrix.juju_channel }}
          sudo su $(whoami) -c 'juju bootstrap localhost --no-gui'
      - name: Run tests
        run: make test-${{ matrix.test_bundles }}
      - name: Display juju debug log on failure
        run: juju debug-log --lines 100
        if: failure()
